# -*- coding: utf-8 -*-
"""Fuzzy3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1evDPxg2oEhqdezyG41mmIqhgxuRkKS67

# Fuzzy TA
"""

pip install scikit-fuzzy

# ==========================================
# CELL 1: SETUP & FUZZIFIKASI
# ==========================================
import numpy as np
import skfuzzy as fuzz
import matplotlib.pyplot as plt

# 1. INISIALISASI SEMESTA PEMBICARAAN (DOMAIN)
x_lcd = np.arange(0, 101, 1)
x_key = np.arange(0, 101, 1)
x_ram = np.arange(4, 65, 1)
x_bat = np.arange(0, 101, 1)
x_bench = np.arange(0, 64947, 1)
y_kelayakan = np.arange(0, 101, 1)

# 2. PEMBENTUKAN FUNGSI KEANGGOTAAN
lcd_buruk = fuzz.trapmf(x_lcd, [0, 0, 55, 65])
lcd_sedang = fuzz.trapmf(x_lcd, [55, 65, 75, 85])
lcd_baik = fuzz.trapmf(x_lcd, [75, 85, 100, 100])

key_buruk = fuzz.trapmf(x_key, [0, 0, 55, 65])
key_sedang = fuzz.trapmf(x_key, [55, 65, 75, 85])
key_baik = fuzz.trapmf(x_key, [75, 85, 100, 100])

ram_rendah = fuzz.trapmf(x_ram, [4, 4, 6, 8])
ram_sedang = fuzz.trimf(x_ram, [6, 8, 12])
ram_tinggi = fuzz.trapmf(x_ram, [8, 12, 64, 64])

bat_rendah = fuzz.trapmf(x_bat, [0, 0, 60, 70])
bat_sedang = fuzz.trimf(x_bat, [60, 70, 85])
bat_tinggi = fuzz.trapmf(x_bat, [70, 85, 100, 100])

bench_rendah = fuzz.trapmf(x_bench, [0, 0, 8000, 10000])
bench_sedang = fuzz.trapmf(x_bench, [8000, 10000, 18000, 20000])
bench_tinggi = fuzz.trapmf(x_bench, [18000, 20000, 64946, 64946])

kelayakan_tidak = fuzz.trapmf(y_kelayakan, [0, 0, 55, 65])
kelayakan_cukup = fuzz.trapmf(y_kelayakan, [55, 65, 85, 90])
kelayakan_layak = fuzz.trapmf(y_kelayakan, [85, 90, 100, 100])

# 3. INPUT DATA UJI LALU LAKUKAN FUZZIFIKASI
val_lcd = 95       # Mulus, tanpa dead pixel
val_key = 95       # Responsif, backlight nyala
val_ram = 16       # 16 GB
val_bat = 95       # Health sangat prima
val_bench = 22082  # AMD Ryzen 9 5900HX

u_lcd_b = fuzz.interp_membership(x_lcd, lcd_buruk, val_lcd)
u_lcd_s = fuzz.interp_membership(x_lcd, lcd_sedang, val_lcd)
u_lcd_k = fuzz.interp_membership(x_lcd, lcd_baik, val_lcd)

u_key_b = fuzz.interp_membership(x_key, key_buruk, val_key)
u_key_s = fuzz.interp_membership(x_key, key_sedang, val_key)
u_key_k = fuzz.interp_membership(x_key, key_baik, val_key)

u_ram_r = fuzz.interp_membership(x_ram, ram_rendah, val_ram)
u_ram_s = fuzz.interp_membership(x_ram, ram_sedang, val_ram)
u_ram_t = fuzz.interp_membership(x_ram, ram_tinggi, val_ram)

u_bat_r = fuzz.interp_membership(x_bat, bat_rendah, val_bat)
u_bat_s = fuzz.interp_membership(x_bat, bat_sedang, val_bat)
u_bat_t = fuzz.interp_membership(x_bat, bat_tinggi, val_bat)

u_bench_r = fuzz.interp_membership(x_bench, bench_rendah, val_bench)
u_bench_s = fuzz.interp_membership(x_bench, bench_sedang, val_bench)
u_bench_t = fuzz.interp_membership(x_bench, bench_tinggi, val_bench)

print(f"Data Input: LCD={val_lcd}, Key={val_key}, RAM={val_ram}, Bat={val_bat}, Bench={val_bench}")
print("\n--- TAHAP 1: HASIL FUZZIFIKASI ---")
print(f"LCD   (B: {u_lcd_b:.2f}, S: {u_lcd_s:.2f}, K: {u_lcd_k:.2f})")
print(f"Key   (B: {u_key_b:.2f}, S: {u_key_s:.2f}, K: {u_key_k:.2f})")
print(f"RAM   (R: {u_ram_r:.2f}, S: {u_ram_s:.2f}, T: {u_ram_t:.2f})")
print(f"Bat   (R: {u_bat_r:.2f}, S: {u_bat_s:.2f}, T: {u_bat_t:.2f})")
print(f"Bench (R: {u_bench_r:.2f}, S: {u_bench_s:.2f}, T: {u_bench_t:.2f})")

# ==========================================
# CELL 2: EVALUASI ATURAN & IMPLIKASI (+KURVA)
# ==========================================
# Struktur Data Aturan (243 Rules)
rules = [
    # --- LCD BURUK, KEYBOARD BURUK (R1-R27) ---
    ([u_lcd_b, u_key_b, u_ram_r, u_bat_r, u_bench_r], kelayakan_tidak),
    ([u_lcd_b, u_key_b, u_ram_r, u_bat_r, u_bench_s], kelayakan_tidak),
    ([u_lcd_b, u_key_b, u_ram_r, u_bat_r, u_bench_t], kelayakan_tidak),
    ([u_lcd_b, u_key_b, u_ram_r, u_bat_s, u_bench_r], kelayakan_tidak),
    ([u_lcd_b, u_key_b, u_ram_r, u_bat_s, u_bench_s], kelayakan_tidak),
    ([u_lcd_b, u_key_b, u_ram_r, u_bat_s, u_bench_t], kelayakan_tidak),
    ([u_lcd_b, u_key_b, u_ram_r, u_bat_t, u_bench_r], kelayakan_tidak),
    ([u_lcd_b, u_key_b, u_ram_r, u_bat_t, u_bench_s], kelayakan_tidak),
    ([u_lcd_b, u_key_b, u_ram_r, u_bat_t, u_bench_t], kelayakan_tidak),
    ([u_lcd_b, u_key_b, u_ram_s, u_bat_r, u_bench_r], kelayakan_tidak),
    ([u_lcd_b, u_key_b, u_ram_s, u_bat_r, u_bench_s], kelayakan_tidak),
    ([u_lcd_b, u_key_b, u_ram_s, u_bat_r, u_bench_t], kelayakan_tidak),
    ([u_lcd_b, u_key_b, u_ram_s, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_b, u_ram_s, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_b, u_ram_s, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_b, u_ram_s, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_b, u_ram_s, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_b, u_ram_s, u_bat_t, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_b, u_ram_t, u_bat_r, u_bench_r], kelayakan_tidak),
    ([u_lcd_b, u_key_b, u_ram_t, u_bat_r, u_bench_s], kelayakan_tidak),
    ([u_lcd_b, u_key_b, u_ram_t, u_bat_r, u_bench_t], kelayakan_tidak),
    ([u_lcd_b, u_key_b, u_ram_t, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_b, u_ram_t, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_b, u_ram_t, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_b, u_ram_t, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_b, u_ram_t, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_b, u_ram_t, u_bat_t, u_bench_t], kelayakan_cukup),

    # --- LCD BURUK, KEYBOARD SEDANG (R28-R54) ---
    ([u_lcd_b, u_key_s, u_ram_r, u_bat_r, u_bench_r], kelayakan_tidak),
    ([u_lcd_b, u_key_s, u_ram_r, u_bat_r, u_bench_s], kelayakan_tidak),
    ([u_lcd_b, u_key_s, u_ram_r, u_bat_r, u_bench_t], kelayakan_tidak),
    ([u_lcd_b, u_key_s, u_ram_r, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_r, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_r, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_r, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_r, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_r, u_bat_t, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_s, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_s, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_s, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_s, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_s, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_s, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_s, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_s, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_s, u_bat_t, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_t, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_t, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_t, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_t, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_t, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_t, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_t, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_t, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_s, u_ram_t, u_bat_t, u_bench_t], kelayakan_cukup),

    # --- LCD BURUK, KEYBOARD BAIK (R55-R81) ---
    ([u_lcd_b, u_key_k, u_ram_r, u_bat_r, u_bench_r], kelayakan_tidak),
    ([u_lcd_b, u_key_k, u_ram_r, u_bat_r, u_bench_s], kelayakan_tidak),
    ([u_lcd_b, u_key_k, u_ram_r, u_bat_r, u_bench_t], kelayakan_tidak),
    ([u_lcd_b, u_key_k, u_ram_r, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_r, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_r, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_r, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_r, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_r, u_bat_t, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_s, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_s, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_s, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_s, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_s, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_s, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_s, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_s, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_s, u_bat_t, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_t, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_t, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_t, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_t, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_t, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_t, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_t, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_t, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_b, u_key_k, u_ram_t, u_bat_t, u_bench_t], kelayakan_cukup),

    # --- LCD SEDANG, KEYBOARD BURUK (R82-R108) ---
    ([u_lcd_s, u_key_b, u_ram_r, u_bat_r, u_bench_r], kelayakan_tidak),
    ([u_lcd_s, u_key_b, u_ram_r, u_bat_r, u_bench_s], kelayakan_tidak),
    ([u_lcd_s, u_key_b, u_ram_r, u_bat_r, u_bench_t], kelayakan_tidak),
    ([u_lcd_s, u_key_b, u_ram_r, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_r, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_r, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_r, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_r, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_r, u_bat_t, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_s, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_s, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_s, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_s, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_s, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_s, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_s, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_s, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_s, u_bat_t, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_t, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_t, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_t, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_t, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_t, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_t, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_t, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_t, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_b, u_ram_t, u_bat_t, u_bench_t], kelayakan_cukup),

    # --- LCD SEDANG, KEYBOARD SEDANG (R109-R135) ---
    ([u_lcd_s, u_key_s, u_ram_r, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_r, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_r, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_r, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_r, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_r, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_r, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_r, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_r, u_bat_t, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_s, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_s, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_s, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_s, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_s, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_s, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_s, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_s, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_s, u_bat_t, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_t, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_t, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_t, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_t, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_t, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_t, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_t, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_t, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_s, u_ram_t, u_bat_t, u_bench_t], kelayakan_cukup),

    # --- LCD SEDANG, KEYBOARD BAIK (R136-R162) ---
    ([u_lcd_s, u_key_k, u_ram_r, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_r, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_r, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_r, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_r, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_r, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_r, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_r, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_r, u_bat_t, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_s, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_s, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_s, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_s, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_s, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_s, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_s, u_bat_t, u_bench_r], kelayakan_layak),
    ([u_lcd_s, u_key_k, u_ram_s, u_bat_t, u_bench_s], kelayakan_layak),
    ([u_lcd_s, u_key_k, u_ram_s, u_bat_t, u_bench_t], kelayakan_layak),
    ([u_lcd_s, u_key_k, u_ram_t, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_t, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_t, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_t, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_t, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_t, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_s, u_key_k, u_ram_t, u_bat_t, u_bench_r], kelayakan_layak),
    ([u_lcd_s, u_key_k, u_ram_t, u_bat_t, u_bench_s], kelayakan_layak),
    ([u_lcd_s, u_key_k, u_ram_t, u_bat_t, u_bench_t], kelayakan_layak),

    # --- LCD BAIK, KEYBOARD BURUK (R163-R189) ---
    ([u_lcd_k, u_key_b, u_ram_r, u_bat_r, u_bench_r], kelayakan_tidak),
    ([u_lcd_k, u_key_b, u_ram_r, u_bat_r, u_bench_s], kelayakan_tidak),
    ([u_lcd_k, u_key_b, u_ram_r, u_bat_r, u_bench_t], kelayakan_tidak),
    ([u_lcd_k, u_key_b, u_ram_r, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_r, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_r, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_r, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_r, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_r, u_bat_t, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_s, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_s, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_s, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_s, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_s, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_s, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_s, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_s, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_s, u_bat_t, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_t, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_t, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_t, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_t, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_t, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_t, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_t, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_t, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_b, u_ram_t, u_bat_t, u_bench_t], kelayakan_cukup),

    # --- LCD BAIK, KEYBOARD SEDANG (R190-R216) ---
    ([u_lcd_k, u_key_s, u_ram_r, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_r, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_r, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_r, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_r, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_r, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_r, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_r, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_r, u_bat_t, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_s, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_s, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_s, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_s, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_s, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_s, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_s, u_bat_t, u_bench_r], kelayakan_layak),
    ([u_lcd_k, u_key_s, u_ram_s, u_bat_t, u_bench_s], kelayakan_layak),
    ([u_lcd_k, u_key_s, u_ram_s, u_bat_t, u_bench_t], kelayakan_layak),
    ([u_lcd_k, u_key_s, u_ram_t, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_t, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_t, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_t, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_t, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_t, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_s, u_ram_t, u_bat_t, u_bench_r], kelayakan_layak),
    ([u_lcd_k, u_key_s, u_ram_t, u_bat_t, u_bench_s], kelayakan_layak),
    ([u_lcd_k, u_key_s, u_ram_t, u_bat_t, u_bench_t], kelayakan_layak),

    # --- LCD BAIK, KEYBOARD BAIK (R217-R243) ---
    ([u_lcd_k, u_key_k, u_ram_r, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_k, u_ram_r, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_k, u_ram_r, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_k, u_ram_r, u_bat_s, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_k, u_ram_r, u_bat_s, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_k, u_ram_r, u_bat_s, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_k, u_ram_r, u_bat_t, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_k, u_ram_r, u_bat_t, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_k, u_ram_r, u_bat_t, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_k, u_ram_s, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_k, u_ram_s, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_k, u_ram_s, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_k, u_ram_s, u_bat_s, u_bench_r], kelayakan_layak),
    ([u_lcd_k, u_key_k, u_ram_s, u_bat_s, u_bench_s], kelayakan_layak),
    ([u_lcd_k, u_key_k, u_ram_s, u_bat_s, u_bench_t], kelayakan_layak),
    ([u_lcd_k, u_key_k, u_ram_s, u_bat_t, u_bench_r], kelayakan_layak),
    ([u_lcd_k, u_key_k, u_ram_s, u_bat_t, u_bench_s], kelayakan_layak),
    ([u_lcd_k, u_key_k, u_ram_s, u_bat_t, u_bench_t], kelayakan_layak),
    ([u_lcd_k, u_key_k, u_ram_t, u_bat_r, u_bench_r], kelayakan_cukup),
    ([u_lcd_k, u_key_k, u_ram_t, u_bat_r, u_bench_s], kelayakan_cukup),
    ([u_lcd_k, u_key_k, u_ram_t, u_bat_r, u_bench_t], kelayakan_cukup),
    ([u_lcd_k, u_key_k, u_ram_t, u_bat_s, u_bench_r], kelayakan_layak),
    ([u_lcd_k, u_key_k, u_ram_t, u_bat_s, u_bench_s], kelayakan_layak),
    ([u_lcd_k, u_key_k, u_ram_t, u_bat_s, u_bench_t], kelayakan_layak),
    ([u_lcd_k, u_key_k, u_ram_t, u_bat_t, u_bench_r], kelayakan_layak),
    ([u_lcd_k, u_key_k, u_ram_t, u_bat_t, u_bench_s], kelayakan_layak),
    ([u_lcd_k, u_key_k, u_ram_t, u_bat_t, u_bench_t], kelayakan_layak),
]

# List untuk menyimpan kurva implikasi yang aktif (untuk di-plot)
active_impl_min_curves = []
active_impl_prod_curves = []

print("\n--- TAHAP 2: RULES YANG AKTIF & PROSES IMPLIKASI ---")
for i, (antecedents, consequent_mf) in enumerate(rules):
    # Kekuatan Aturan (T-Norm)
    a_predikat = np.min(antecedents)
    a_predikat_prod = np.prod(antecedents)

    if a_predikat > 0 or a_predikat_prod > 0:
        print(f"Rule {i+1} Aktif | Kekuatan (Min): {a_predikat:.3f} | Kekuatan (Prod): {a_predikat_prod:.3f}")

        # Proses Implikasi (THEN)
        implikasi_min = np.fmin(a_predikat, consequent_mf)
        implikasi_prod = a_predikat_prod * consequent_mf

        # Simpan kurva ini untuk digambar
        active_impl_min_curves.append((i+1, implikasi_min))
        active_impl_prod_curves.append((i+1, implikasi_prod))

# --- GAMBAR KURVA IMPLIKASI ---
fig_imp, (ax_imp_min, ax_imp_prod) = plt.subplots(nrows=1, ncols=2, figsize=(14, 4))

for rule_num, curve in active_impl_min_curves:
    ax_imp_min.plot(y_kelayakan, curve, linewidth=2, label=f'Rule {rule_num} (Min)')
    ax_imp_min.fill_between(y_kelayakan, 0, curve, alpha=0.3)
ax_imp_min.set_title('Tahap Implikasi (Mamdani-Min / Clipping)')
ax_imp_min.legend()

for rule_num, curve in active_impl_prod_curves:
    ax_imp_prod.plot(y_kelayakan, curve, linewidth=2, label=f'Rule {rule_num} (Prod)')
    ax_imp_prod.fill_between(y_kelayakan, 0, curve, alpha=0.3)
ax_imp_prod.set_title('Tahap Implikasi (Mamdani-Product / Scaling)')
ax_imp_prod.legend()

plt.tight_layout()
plt.show()

# ==========================================
# CELL 3: TAHAP AGREGASI (+KURVA)
# ==========================================
# Siapkan canvas kosong
agregasi_min = np.zeros_like(y_kelayakan)
agregasi_prod = np.zeros_like(y_kelayakan)

# Tumpuk semua kurva implikasi menggunakan MAX (Union)
for _, curve in active_impl_min_curves:
    agregasi_min = np.fmax(agregasi_min, curve)

for _, curve in active_impl_prod_curves:
    agregasi_prod = np.fmax(agregasi_prod, curve)

print("\n--- TAHAP 3: AGREGASI SELESAI ---")
print("Semua kurva implikasi telah digabungkan membentuk kurva agregasi akhir.")

# --- GAMBAR KURVA AGREGASI ---
fig_agr, (ax_agr_min, ax_agr_prod) = plt.subplots(nrows=1, ncols=2, figsize=(14, 4))

ax_agr_min.plot(y_kelayakan, agregasi_min, 'orange', linewidth=2)
ax_agr_min.fill_between(y_kelayakan, 0, agregasi_min, facecolor='orange', alpha=0.7)
ax_agr_min.set_title('Hasil Agregasi Mamdani-Min')

ax_agr_prod.plot(y_kelayakan, agregasi_prod, 'purple', linewidth=2)
ax_agr_prod.fill_between(y_kelayakan, 0, agregasi_prod, facecolor='purple', alpha=0.7)
ax_agr_prod.set_title('Hasil Agregasi Mamdani-Product')

plt.tight_layout()
plt.show()

# ==========================================
# CELL 4: TAHAP DEFUZZIFIKASI TERAKHIR
# ==========================================
if np.sum(agregasi_min) == 0 or np.sum(agregasi_prod) == 0:
    print("Error: Tidak ada data area yang bisa di-defuzzifikasi.")
else:
    # Perhitungan Matematika Centroid & Bisector
    out_min_coa = fuzz.defuzz(y_kelayakan, agregasi_min, 'centroid')
    out_min_bis = fuzz.defuzz(y_kelayakan, agregasi_min, 'bisector')

    out_prod_coa = fuzz.defuzz(y_kelayakan, agregasi_prod, 'centroid')
    out_prod_bis = fuzz.defuzz(y_kelayakan, agregasi_prod, 'bisector')

    print("\n--- TAHAP 4: HASIL SKOR KELAYAKAN FINAL ---")
    print("1. Metode Mamdani-Min:")
    print(f"   - Centroid (CoA) : {out_min_coa:.2f}")
    print(f"   - Bisector       : {out_min_bis:.2f}\n")

    print("2. Metode Mamdani-Product:")
    print(f"   - Centroid (CoA) : {out_prod_coa:.2f}")
    print(f"   - Bisector       : {out_prod_bis:.2f}\n")

    # --- GAMBAR GARIS DEFUZZIFIKASI ---
    fig_def, (ax_def_min, ax_def_prod) = plt.subplots(nrows=2, figsize=(10, 8))

    # Grafik Atas (Mamdani-Min)
    ax_def_min.plot(y_kelayakan, kelayakan_tidak, 'b--', linewidth=1, alpha=0.5)
    ax_def_min.plot(y_kelayakan, kelayakan_cukup, 'g--', linewidth=1, alpha=0.5)
    ax_def_min.plot(y_kelayakan, kelayakan_layak, 'r--', linewidth=1, alpha=0.5)
    ax_def_min.fill_between(y_kelayakan, 0, agregasi_min, facecolor='orange', alpha=0.7)
    # Garis Pembelah
    ax_def_min.vlines(out_min_coa, 0, 1.1, colors='black', linestyles='-', linewidth=2, label=f'Centroid: {out_min_coa:.2f}')
    ax_def_min.vlines(out_min_bis, 0, 1.1, colors='blue', linestyles='-.', linewidth=2, label=f'Bisector: {out_min_bis:.2f}')
    ax_def_min.set_title('Defuzzifikasi Mamdani-Min')
    ax_def_min.legend()

    # Grafik Bawah (Mamdani-Product)
    ax_def_prod.plot(y_kelayakan, kelayakan_tidak, 'b--', linewidth=1, alpha=0.5)
    ax_def_prod.plot(y_kelayakan, kelayakan_cukup, 'g--', linewidth=1, alpha=0.5)
    ax_def_prod.plot(y_kelayakan, kelayakan_layak, 'r--', linewidth=1, alpha=0.5)
    ax_def_prod.fill_between(y_kelayakan, 0, agregasi_prod, facecolor='purple', alpha=0.7)
    # Garis Pembelah
    ax_def_prod.vlines(out_prod_coa, 0, 1.1, colors='black', linestyles='-', linewidth=2, label=f'Centroid: {out_prod_coa:.2f}')
    ax_def_prod.vlines(out_prod_bis, 0, 1.1, colors='blue', linestyles='-.', linewidth=2, label=f'Bisector: {out_prod_bis:.2f}')
    ax_def_prod.set_title('Defuzzifikasi Mamdani-Product')
    ax_def_prod.legend()

    plt.tight_layout()
    plt.show()