import type { Config } from 'tailwindcss'
import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

const config: Config = {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#455f88',
        'primary-fixed': '#d6e3ff',
        'secondary-fixed-dim': '#bdc7dc',
        'on-primary-fixed': '#001b3c',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#121c2c',
        'surface-container-highest': '#e3e2e6',
        'secondary-container': '#d6e0f6',
        'inverse-surface': '#2f3033',
        'on-tertiary-container': '#c6955e',
        'on-secondary-fixed-variant': '#3d4759',
        'surface-dim': '#dad9dd',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-background': '#1a1c1e',
        outline: '#74777f',
        'on-tertiary-fixed-variant': '#633f0f',
        'on-tertiary-fixed': '#2b1700',
        error: '#ba1a1a',
        'surface-variant': '#e3e2e6',
        'outline-variant': '#c4c6cf',
        'surface-container-high': '#e9e7eb',
        secondary: '#555f71',
        'surface-container': '#efedf1',
        'surface-bright': '#faf9fd',
        'on-surface-variant': '#43474e',
        'inverse-on-surface': '#f1f0f4',
        'inverse-primary': '#adc7f7',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#adc7f7',
        surface: '#faf9fd',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#ffddba',
        background: '#faf9fd',
        'on-primary-container': '#86a0cd',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#2d476f',
        'on-error': '#ffffff',
        'on-surface': '#1a1c1e',
        'on-secondary-container': '#596376',
        'surface-container-low': '#f4f3f7',
        'tertiary-container': '#4f2e00',
        primary: '#002045',
        tertiary: '#321b00',
        'primary-container': '#1a365d',
        'tertiary-fixed-dim': '#f2bc82',
        'secondary-fixed': '#d9e3f9',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        lg: '24px',
        margin: '32px',
        gutter: '20px',
        md: '16px',
        xs: '4px',
        sm: '8px',
        unit: '4px',
        xl: '40px',
      },
      fontFamily: {
        h2: ['Inter'],
        'body-lg': ['Inter'],
        caption: ['Inter'],
        'body-md': ['Inter'],
        h3: ['Inter'],
        h1: ['Inter'],
        'label-bold': ['Inter'],
      },
      fontSize: {
        h2: ['30px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        h3: ['24px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '700' }],
        h1: ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-bold': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [forms, containerQueries],
}

export default config
