<template>
  <section class="space-y-xl">
    <div class="flex flex-wrap items-end justify-between gap-md"><div><h1 class="font-h1 text-h1 text-primary">Data Laptop</h1><p class="mt-sm text-on-surface-variant">Kelola model laptop dan spesifikasinya.</p></div><button class="rounded-full bg-primary px-lg py-md font-bold text-white" @click="startCreate">Tambah Data Laptop</button></div>
    <form v-if="showForm" class="grid gap-md rounded-[24px] bg-surface p-xl shadow-sm md:grid-cols-2" @submit.prevent="save"><h2 class="font-h3 text-h3 text-primary md:col-span-2">{{ editing ? 'Edit Data Laptop' : 'Tambah Data Laptop' }}</h2><select v-model="form.brand_name" required class="rounded-2xl border border-outline-variant/50 bg-surface-container px-lg py-md"><option value="">Pilih brand</option><option v-for="brand in brands" :key="brand.id" :value="brand.name">{{ brand.name }}</option></select><input v-model="form.model_name" required class="rounded-2xl border border-outline-variant/50 bg-surface-container px-lg py-md" placeholder="Model laptop" /><input v-model="form.processor_name" required class="rounded-2xl border border-outline-variant/50 bg-surface-container px-lg py-md" placeholder="Processor" /><input v-model.number="form.benchmark_score" required min="0" type="number" class="rounded-2xl border border-outline-variant/50 bg-surface-container px-lg py-md" placeholder="Benchmark" /><button class="rounded-full bg-primary px-xl py-md font-bold text-white md:col-span-2">Simpan</button></form>
    <div class="flex flex-col gap-sm rounded-2xl bg-surface p-md shadow-sm sm:flex-row sm:items-center"><label for="brand-filter" class="font-bold text-primary">Filter Brand</label><select id="brand-filter" v-model="filterBrandId" class="w-full rounded-xl border border-outline-variant/50 bg-surface-container px-md py-sm sm:flex-1" @change="loadLaptops"><option :value="null">Semua brand</option><option v-for="brand in brands" :key="brand.id" :value="brand.id">{{ brand.name }}</option></select></div>
    <div class="overflow-x-auto rounded-[24px] border border-outline-variant/30 bg-surface shadow-[0_8px_40px_rgba(0,0,0,0.03)]"><table class="w-full min-w-[900px] text-left"><thead><tr class="border-b border-outline-variant/30 bg-surface-container/50"><th class="px-lg py-md text-[12px] uppercase tracking-wider text-primary">Brand</th><th class="px-lg py-md text-[12px] uppercase tracking-wider text-primary">Model Laptop</th><th class="px-lg py-md text-[12px] uppercase tracking-wider text-primary">Processor</th><th class="px-lg py-md text-[12px] uppercase tracking-wider text-primary">Benchmark</th><th class="px-lg py-md text-center text-[12px] uppercase tracking-wider text-primary">Aksi</th></tr></thead><tbody><tr v-for="laptop in laptops" :key="laptop.id" class="border-b border-outline-variant/20 last:border-0"><td class="px-lg py-md font-bold text-primary">{{ laptop.brand.name }}</td><td class="px-lg py-md">{{ laptop.model_name }}</td><td class="px-lg py-md text-on-surface-variant">{{ laptop.processor_name }}</td><td class="px-lg py-md"><span class="rounded-full bg-primary/10 px-sm py-xs font-bold text-primary">{{ laptop.benchmark_score }}</span></td><td class="px-lg py-md"><div class="flex justify-center gap-md"><button class="font-bold text-primary hover:underline" @click="startEdit(laptop)">Edit</button><button class="font-bold text-error hover:underline" @click="remove(laptop)">Hapus</button></div></td></tr></tbody></table><p v-if="!laptops.length" class="p-xl text-center text-on-surface-variant">Belum ada data laptop.</p></div>
  </section>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import Swal from 'sweetalert2'
import type { Laptop, LaptopBrand } from '@/constants/assessment'
import { evaluationService } from '@/services/evaluation'
defineOptions({ name: 'LaptopData' })
const { getLaptopBrands, getLaptops, createLaptop, updateLaptop, deleteLaptop } = evaluationService(); const brands = ref<LaptopBrand[]>([]); const laptops = ref<Laptop[]>([]); const filterBrandId = ref<number | null>(null); const showForm = ref(false); const editing = ref<Laptop | null>(null); const form = reactive({ brand_name: '', model_name: '', processor_name: '', benchmark_score: 0 })
const loadLaptops = async () => { laptops.value = await getLaptops(filterBrandId.value ?? undefined) }; const load = async () => { brands.value = await getLaptopBrands(); await loadLaptops() }; const startCreate = () => { editing.value = null; Object.assign(form, { brand_name: '', model_name: '', processor_name: '', benchmark_score: 0 }); showForm.value = true }; const startEdit = (laptop: Laptop) => { editing.value = laptop; Object.assign(form, { brand_name: laptop.brand.name, model_name: laptop.model_name, processor_name: laptop.processor_name, benchmark_score: laptop.benchmark_score }); showForm.value = true }
const save = async () => { const brand = brands.value.find((item) => item.name === form.brand_name); if (!brand) return; if (editing.value) await updateLaptop(editing.value.id, { brand_id: brand.id, model_name: form.model_name, processor_name: form.processor_name, benchmark_score: form.benchmark_score }); else await createLaptop(form); await loadLaptops(); showForm.value = false; await Swal.fire({ title: 'Berhasil', text: 'Data laptop tersimpan.', icon: 'success', timer: 1400, showConfirmButton: false }) }
const remove = async (laptop: Laptop) => { const result = await Swal.fire({ title: 'Hapus data laptop?', text: laptop.model_name, icon: 'warning', showCancelButton: true, confirmButtonText: 'Hapus', cancelButtonText: 'Batal' }); if (!result.isConfirmed) return; await deleteLaptop(laptop.id); await loadLaptops() }
onMounted(load)
</script>
